# Generated by Django 2.1 on 2021-11-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_config', models.TextField()),
                ('create_date', models.CharField(max_length=45)),
                ('create_person_id', models.IntegerField()),
            ],
            options={
                'db_table': 'device_configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'operator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mytools.DeviceConfiguration')),
                ('device_name', models.CharField(blank=True, max_length=45, null=True)),
                ('device_location', models.CharField(blank=True, max_length=45, null=True)),
                ('device_username', models.CharField(max_length=45)),
                ('device_password', models.CharField(max_length=45)),
                ('device_secret', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'device',
                'managed': False,
            },
        ),
    ]
